### ISSUE TITLE
Configure default settings in configuration files

### ISSUE THREAD

**Issue by thiezn** [thiezn/awsaccountmgr#1]
It would be nice to be able to set the configuration file defaults in each file. This would make the file more readable and ensure consistency between accounts.

An example could be:

```yaml
Defaults:
    DeleteDefaultVPC: True
    AllowDirectMoveBetweenOU: True
    AllowBilling: False
    Tags:
      - CostCenter: 123456789

Accounts:
  - AccountFullName: myrootaccount
    OrganizationalUnitPath: r-abc1
    Email: myrootaccount@moorspots.com
```
